############# English navigation ##############

# main menu
# No main menu items - logo left, Let's Talk button right


# footer menu
[[footer]]
name = "Home"
url = "/#home"
weight = 1

[[footer]]
name = "About"
url = "/#about"
weight = 2

[[footer]]
name = "Services"
url = "/#services"
weight = 3

[[footer]]
name = "Contact"
url = "/#contact"
weight = 4
