############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/#home"
weight = 1

[[main]]
name = "About"
url = "/#about"
weight = 2

[[main]]
name = "Services"
url = "/#services"
weight = 3

[[main]]
name = "Contact"
url = "/#contact"
weight = 4


# footer menu
[[footer]]
name = "Home"
url = "/#home"
weight = 1

[[footer]]
name = "About"
url = "/#about"
weight = 2

[[footer]]
name = "Services"
url = "/#services"
weight = 3

[[footer]]
name = "Contact"
url = "/#contact"
weight = 4
